#!/usr/bin/lua

local nixio = require "nixio"

local PORT = 8888
local MAX_REQUEST = 1023
local ACK = "OK\r\n"

local server, message = nixio.socket("inet", "stream")
if not server then
	io.stderr:write("unable to create local APP socket: ",
		tostring(message), "\n")
	os.exit(1)
end

server:setopt("socket", "reuseaddr", 1)
local bound, bind_message = server:bind("0.0.0.0", PORT)
if not bound then
	io.stderr:write("unable to bind local APP socket: ",
		tostring(bind_message), "\n")
	server:close()
	os.exit(1)
end

local listening, listen_message = server:listen(100)
if not listening then
	io.stderr:write("unable to listen on local APP socket: ",
		tostring(listen_message), "\n")
	server:close()
	os.exit(1)
end

require("c2000max_app.server").run(server, function(client)
	local request = client:recv(MAX_REQUEST)
	if request and #request > 0 then
		client:send(ACK)
	end
end, { workers = 8, io_timeout = 3, timeout = 5 })
